services:
  # The Public Web Service
  - type: web
    name: jitsi-web
    env: image
    image:
      url: jitsi/web:latest # Use the 'latest' reliable tag
    plan: free
    healthCheckPath: /
    envVars:
      - key: PUBLIC_URL
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: XMPP_SERVER
        value: jitsi-prosody
      - key: XMPP_DOMAIN
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: XMPP_BOSH_URL_BASE
        value: http://jitsi-prosody:5280
      - key: JICOFO_AUTH_USER
        value: jicofo
      - key: TZ
        value: Etc/UTC
      - key: ENABLE_AUTH
        value: "1"
      - key: ENABLE_GUESTS
        value: "0"
      - key: AUTH_TYPE
        value: internal

  # The Video Bridge
  - type: pserv
    name: jitsi-jvb
    env: image
    image:
      url: jitsi/jvb:latest # Use the 'latest' reliable tag
    plan: free
    envVars:
      - key: XMPP_SERVER
        value: jitsi-prosody
      - key: XMPP_DOMAIN
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: JVB_AUTH_USER
        value: jvb
      - key: JVB_STUN_SERVERS
        value: "stun.l.google.com:19302,stun.jitsi.net:4443"
      - key: JICOFO_AUTH_USER
        value: jicofo

  # The User/Authentication Server
  - type: pserv
    name: jitsi-prosody
    env: image
    image:
      url: jitsi/prosody:latest # Use the 'latest' reliable tag
    plan: free
    envVars:
      - key: XMPP_DOMAIN
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: JICOFO_AUTH_USER
        value: jicofo
      - key: JVB_AUTH_USER
        value: jvb

  # The Conference Manager
  - type: pserv
    name: jitsi-jicofo
    env: image
    image:
      url: jitsi/jicofo:latest # Use the 'latest' reliable tag
    plan: free
    envVars:
      - key: XMPP_SERVER
        value: jitsi-prosody
      - key: XMPP_DOMAIN
        value: ${RENDER_EXTERNAL_HOSTNAME}
      - key: JICOFO_AUTH_USER
        value: jicofo
